// This file is generated by the ExoQuery Code Generator. Do not modify.
package io.exoquery.example.public

import io.exoquery.annotation.ExoValue
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("org_accountmembers")
data class OrgAccountMembers(
  @SerialName("org_member_id") val orgMemberId: Int,
  @SerialName("org_id") val orgId: Int,
  @SerialName("user_id") val userId: Int,
  @SerialName("role_name") val roleName: String
)