// This file is generated by the ExoQuery Code Generator. Do not modify.
package io.exoquery.example.public

import io.exoquery.annotation.ExoValue
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("Organization_Accounts")
data class OrganizationAccounts(
  @SerialName("orgId") val orgId: Int,
  @SerialName("org_name") val orgName: String,
  @SerialName("legal_name") val legalName: String?,
  @SerialName("created_on") val createdOn: kotlinx.datetime.LocalDate,
  @SerialName("is_active") val isActive: Boolean
)