// This file is generated by the ExoQuery Code Generator. Do not modify.
package io.exoquery.example.public

import io.exoquery.annotation.ExoValue
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("UserProfiles")
data class UserProfiles(
  @SerialName("userId") val userId: Int,
  @SerialName("firstName") val firstName: String,
  @SerialName("last_name") val lastName: String,
  @SerialName("emailAddress") val emailAddress: String,
  @SerialName("isActive") val isActive: Int,
  @SerialName("updated_at") val updatedAt: kotlinx.datetime.LocalDateTime?
)