// This file is generated by the ExoQuery Code Generator. Do not modify.
package io.exoquery.example.public

import io.exoquery.annotation.ExoValue
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("org_account_members")
data class OrgAccountMembers(
  val id: Int,
  @SerialName("org_id") val orgId: Int,
  @SerialName("user_id") val userId: Int,
  @SerialName("role_name") val roleName: String,
  @SerialName("joined_at") val joinedAt: kotlinx.datetime.LocalDateTime
)