// This file is generated by the ExoQuery Code Generator. Do not modify.
package io.exoquery.example.public

import io.exoquery.annotation.ExoValue
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("user_profiles")
data class UserProfiles(
  val id: Int,
  @SerialName("first_name") val firstName: String,
  @SerialName("last_name") val lastName: String,
  @SerialName("email_address") val emailAddress: String,
  @SerialName("is_active") val isActive: Int,
  @SerialName("created_at") val createdAt: kotlinx.datetime.LocalDateTime,
  @SerialName("updated_at") val updatedAt: kotlinx.datetime.LocalDateTime?
)